version: '3.8'
services:
    fastapi:
        build: .
        ports:
        - "8000:8000"
        command: uvicorn main:app --reload
        volumes:
        - .:/app
        depends_on:
        - mysql-db
    mysql-db:
        container_name: mysql-db
        image: mysql:latest
        environment:
            - MYSQL_DATABASE='bookstore'
            - MYSQL_ROOT_PASSWORD='micolash12'
        expose:
            - "3307"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
  db_data: